// <auto-generated />
using Knjizara.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Knjizara.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230503115001_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Knjizara.Model.Izdavac", b =>
                {
                    b.Property<int>("IdIzdavac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIzdavac"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drzava")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazivIzdavaca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdIzdavac");

                    b.ToTable("Izdavacs");
                });

            modelBuilder.Entity("Knjizara.Model.Knjiga", b =>
                {
                    b.Property<int>("IdKnjige")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKnjige"));

                    b.Property<int>("BrojStranica")
                        .HasColumnType("int");

                    b.Property<int>("IdIzdavac")
                        .HasColumnType("int");

                    b.Property<int>("IdPisca")
                        .HasColumnType("int");

                    b.Property<int>("IdPovez")
                        .HasColumnType("int");

                    b.Property<int>("IdZanr")
                        .HasColumnType("int");

                    b.Property<string>("NazivKnjige")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKnjige");

                    b.ToTable("Knjigas");
                });

            modelBuilder.Entity("Knjizara.Model.Korisnik", b =>
                {
                    b.Property<int>("IdClana")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClana"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drzava")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ulogaClana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdClana");

                    b.ToTable("Korisniks");
                });

            modelBuilder.Entity("Knjizara.Model.Korpa", b =>
                {
                    b.Property<int>("IdKorpa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKorpa"));

                    b.Property<int>("IdKorisnik")
                        .HasColumnType("int");

                    b.Property<int>("IdStavkaKorpe")
                        .HasColumnType("int");

                    b.HasKey("IdKorpa");

                    b.ToTable("Korpaks");
                });

            modelBuilder.Entity("Knjizara.Model.NacinPlacanja", b =>
                {
                    b.Property<int>("IdNacinPlacanja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNacinPlacanja"));

                    b.Property<string>("NazivNacinPlacanja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNacinPlacanja");

                    b.ToTable("NacinPlacanjas");
                });

            modelBuilder.Entity("Knjizara.Model.Pisac", b =>
                {
                    b.Property<int>("IdPisca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPisca"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPisca");

                    b.ToTable("Pisacs");
                });

            modelBuilder.Entity("Knjizara.Model.Povez", b =>
                {
                    b.Property<int>("IdPovez")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPovez"));

                    b.Property<string>("NazivPoveza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPovez");

                    b.ToTable("Povezs");
                });

            modelBuilder.Entity("Knjizara.Model.Racun", b =>
                {
                    b.Property<int>("IdRacun")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRacun"));

                    b.Property<string>("Datum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdKorisnik")
                        .HasColumnType("int");

                    b.Property<int>("IdKorpa")
                        .HasColumnType("int");

                    b.Property<int>("IdNacinPlacanja")
                        .HasColumnType("int");

                    b.Property<string>("Vreme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRacun");

                    b.ToTable("Racuns");
                });

            modelBuilder.Entity("Knjizara.Model.StavkaKorpe", b =>
                {
                    b.Property<int>("IdStavkaKorpe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStavkaKorpe"));

                    b.Property<double>("Cena")
                        .HasColumnType("float");

                    b.Property<int>("IdKnjige")
                        .HasColumnType("int");

                    b.Property<int>("IdKorpa")
                        .HasColumnType("int");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.HasKey("IdStavkaKorpe");

                    b.ToTable("StavkaKorpes");
                });

            modelBuilder.Entity("Knjizara.Model.TipKorisnika", b =>
                {
                    b.Property<int>("IdTipKorisnika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipKorisnika"));

                    b.Property<string>("NazivTipaKorisnika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipKorisnika");

                    b.ToTable("TipKorisnikas");
                });

            modelBuilder.Entity("Knjizara.Model.Zanr", b =>
                {
                    b.Property<int>("IdZanr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZanr"));

                    b.Property<string>("NazivZanr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdZanr");

                    b.ToTable("Zanrs");
                });
#pragma warning restore 612, 618
        }
    }
}
